#!/bin/bash

function eslintStagedJavascriptFiles() {
  git diff --name-only --cached | grep js$ | xargs eslint
}

function runUnitTests() {
  npm run test
}

eslintStagedJavascriptFiles
runUnitTests
