#!/bin/bash

function eslintStagedJavascriptFiles() {
  git diff --name-only --cached | grep js$ | xargs standard
}

function runUnitTests() {
  npm run test
}

eslintStagedJavascriptFiles
runUnitTests
